import { XataClient } from './xata'; // This will be generated by Xata

// Initialize Xata client
export const xata = new XataClient({
  apiKey: process.env.XATA_API_KEY,
  branch: process.env.XATA_BRANCH || 'main',
});

// Database schema (to be created in Xata dashboard)
/*
Tables needed:
1. users
   - id (text, primary key)
   - email (text, unique)
   - phone (text, unique)
   - name (text)
   - image (text)
   - createdAt (datetime)
   - lastLogin (datetime)

2. accounts (for NextAuth)
   - id (text)
   - userId (text)
   - type (text)
   - provider (text)
   - providerAccountId (text)
   - refresh_token (text)
   - access_token (text)
   - expires_at (int)
   - token_type (text)
   - scope (text)
   - id_token (text)
   - session_state (text)

3. sessions (for NextAuth)
   - id (text)
   - sessionToken (text)
   - userId (text)
   - expires (datetime)

4. verificationTokens (for NextAuth)
   - identifier (text)
   - token (text)
   - expires (datetime)

5. posts
   - id (text)
   - userId (text)
   - mediaUrl (text)
   - mediaType (text)
   - caption (text)
   - expiresAt (datetime)
   - createdAt (datetime)
   - views (int)

6. likes
   - id (text)
   - userId (text)
   - postId (text)
   - createdAt (datetime)

7. comments
   - id (text)
   - userId (text)
   - postId (text)
   - content (text)
   - createdAt (datetime)
*/
