import { XataClient } from './xata'; // Generated by Xata CLI

export const getXataClient = () => {
  if (!process.env.XATA_API_KEY) {
    throw new Error('XATA_API_KEY not set');
  }
  
  return new XataClient({
    databaseURL: process.env.XATA_DATABASE_URL,
    branch: process.env.XATA_BRANCH || 'main',
    apiKey: process.env.XATA_API_KEY,
  });
};
